/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f1xx.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void GPIO_Config (void);
void Delay (uint32_t time);

int main(void)
{
	SystemInit();
	GPIO_Config();

	GPIOB->ODR &= ~(0b1111 << 12); // turn of 4 LEDs

    /* Loop forever */
	for(;;)
	{
		for (int i = 0; i < 4; ++i) {
		uint16_t mask = (1 << 12) << i;
			GPIOB->ODR |= mask;
			Delay(1000000);
		}

		for (int i = 0; i < 4; ++i) {
			uint32_t mask = (1 << 28) << i; //
			GPIOB->BSRR |= mask;
			Delay(1000000);
		}
	}
}

void GPIO_Config (void)
{
	// Set IOPB EN
	RCC->APB2ENR |= (1 << 3); // Enable GPIOB clock

	// Set MODE12[1:0] = 01: : Output mode, max speed 10 MHz
	GPIOB->CRH |= (1 << 16) | (1 << 20) | (1 << 24) | (1 << 28); // set bit 16, 20, 24, 28
	GPIOB->CRH &= ~((1 << 17) | (1 << 21) | (1 << 25) | (1 << 29)); // clear bit 17, 21, 25, 29

	// Clear  CNF12[1:0]: General purpose output push-pull
	GPIOB->CRH &= ~((0b11 << 18) | (0b11 << 22) | (0b11 << 26) | (0b11 << 30));
}

void Delay (uint32_t time)
{
    while (time--);
}
